/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { assignTaskToProject } from '../fn/project/assign-task-to-project';
import { AssignTaskToProject$Params } from '../fn/project/assign-task-to-project';
import { createProject } from '../fn/project/create-project';
import { CreateProject$Params } from '../fn/project/create-project';
import { deleteProject } from '../fn/project/delete-project';
import { DeleteProject$Params } from '../fn/project/delete-project';
import { getProjectById } from '../fn/project/get-project-by-id';
import { GetProjectById$Params } from '../fn/project/get-project-by-id';
import { listProjects } from '../fn/project/list-projects';
import { ListProjects$Params } from '../fn/project/list-projects';
import { Project } from '../models/project';
import { Task } from '../models/task';
import { updateProject } from '../fn/project/update-project';
import { UpdateProject$Params } from '../fn/project/update-project';

@Injectable({ providedIn: 'root' })
export class ProjectService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listProjects()` */
  static readonly ListProjectsPath = '/project';

  /**
   * Liste aller Projekte.
   *
   * Liefert eine Liste aller vorhandenen Projekte.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listProjects()` instead.
   *
   * This method doesn't expect any request body.
   */
  listProjects$Response(params?: ListProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Project>>> {
    return listProjects(this.http, this.rootUrl, params, context);
  }

  /**
   * Liste aller Projekte.
   *
   * Liefert eine Liste aller vorhandenen Projekte.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listProjects$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listProjects(params?: ListProjects$Params, context?: HttpContext): Observable<Array<Project>> {
    return this.listProjects$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Project>>): Array<Project> => r.body)
    );
  }

  /** Path part for operation `createProject()` */
  static readonly CreateProjectPath = '/project';

  /**
   * Erstellt ein neues Projekt.
   *
   * Erstellt ein neues Projekt
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProject$Response(params: CreateProject$Params, context?: HttpContext): Observable<StrictHttpResponse<Project>> {
    return createProject(this.http, this.rootUrl, params, context);
  }

  /**
   * Erstellt ein neues Projekt.
   *
   * Erstellt ein neues Projekt
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProject(params: CreateProject$Params, context?: HttpContext): Observable<Project> {
    return this.createProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<Project>): Project => r.body)
    );
  }

  /** Path part for operation `getProjectById()` */
  static readonly GetProjectByIdPath = '/project/{id}';

  /**
   * Einzelnes Projekt abrufen.
   *
   * Liefert ein Projekt anhand seiner ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProjectById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectById$Response(params: GetProjectById$Params, context?: HttpContext): Observable<StrictHttpResponse<Project>> {
    return getProjectById(this.http, this.rootUrl, params, context);
  }

  /**
   * Einzelnes Projekt abrufen.
   *
   * Liefert ein Projekt anhand seiner ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProjectById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProjectById(params: GetProjectById$Params, context?: HttpContext): Observable<Project> {
    return this.getProjectById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Project>): Project => r.body)
    );
  }

  /** Path part for operation `updateProject()` */
  static readonly UpdateProjectPath = '/project/{id}';

  /**
   * Projekt aktualisieren.
   *
   * Aktualisiert ein bestehendes Projekt anhand seiner ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProject$Response(params: UpdateProject$Params, context?: HttpContext): Observable<StrictHttpResponse<Project>> {
    return updateProject(this.http, this.rootUrl, params, context);
  }

  /**
   * Projekt aktualisieren.
   *
   * Aktualisiert ein bestehendes Projekt anhand seiner ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProject(params: UpdateProject$Params, context?: HttpContext): Observable<Project> {
    return this.updateProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<Project>): Project => r.body)
    );
  }

  /** Path part for operation `deleteProject()` */
  static readonly DeleteProjectPath = '/project/{id}';

  /**
   * Projekt löschen.
   *
   * Löscht ein Projekt anhand der ID.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteProject()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProject$Response(params: DeleteProject$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteProject(this.http, this.rootUrl, params, context);
  }

  /**
   * Projekt löschen.
   *
   * Löscht ein Projekt anhand der ID.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteProject$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProject(params: DeleteProject$Params, context?: HttpContext): Observable<void> {
    return this.deleteProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `assignTaskToProject()` */
  static readonly AssignTaskToProjectPath = '/project/assignTask';

  /**
   * Eine Aufgabe einem Projekt zuweisen.
   *
   * Weist eine bestehende Aufgabe einem Projekt zu. Eine Aufgabe kann genau einem Projekt zugeordnet sein.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignTaskToProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignTaskToProject$Response(params: AssignTaskToProject$Params, context?: HttpContext): Observable<StrictHttpResponse<Task>> {
    return assignTaskToProject(this.http, this.rootUrl, params, context);
  }

  /**
   * Eine Aufgabe einem Projekt zuweisen.
   *
   * Weist eine bestehende Aufgabe einem Projekt zu. Eine Aufgabe kann genau einem Projekt zugeordnet sein.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignTaskToProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  assignTaskToProject(params: AssignTaskToProject$Params, context?: HttpContext): Observable<Task> {
    return this.assignTaskToProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<Task>): Task => r.body)
    );
  }

}
