/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskStatus } from '../models/task-status';
export interface CreateTask {
  description?: string;
  status?: TaskStatus;
  title?: string;
}
