/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Task } from '../models/task';
export interface Project {
  createdAt?: string;
  description?: string;
  id?: number;
  name?: string;
  tasks?: Array<Task>;
  updatedAt?: string;
}
