/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Status einer Aufgabe
 */
export enum TaskStatus {
  Offen = 'OFFEN',
  InBearbeitung = 'IN_BEARBEITUNG',
  Erledigt = 'ERLEDIGT'
}
