/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskStatus } from '../models/task-status';
export interface Task {
  createdAt?: string;
  description?: string;
  id?: number;
  projectId?: number;
  status?: TaskStatus;
  title?: string;
  updatedAt?: string;
}
