/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTask {
  description?: string;
  projectId?: number;
  status?: TaskStatus;
  title?: string;
}
